spring.datasource.url=jdbc:mysql://localhost:7001/kickzo
spring.datasource.username=kickzo
spring.datasource.password=test123
spring.kafka.bootstrap-servers=localhost:19092

spring.data.redis.database=3
spring.data.redis.host=localhost
spring.data.redis.port=7003
spring.data.redis.timeout=60000

spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=test123
spring.elasticsearch.connection-timeout=10s
spring.elasticsearch.socket-timeout=30s