spring.application.name=stomp_chat

server.port=8200
spring.websocket.enabled=true


# ?? ???? (?? ??)
spring.profiles.active=dev

spring.kafka.consumer.group-id=my-group-${server.port}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.auto-offset-reset=earliest

# Actuator ????? ?? ??
management.endpoints.web.exposure.include=health,metrics,prometheus

# Prometheus ??? ?? ???
management.prometheus.metrics.export.enabled=true
management.metrics.web.server.request.auto-timeouts=true

# ????? ??? ?? ??? ??? ??
# Actuator ???? ?? (???? 8080)
management.server.port=8080
