version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb-container
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: kickzo
            MONGO_INITDB_ROOT_PASSWORD: test123
            MONGO_INITDB_DATABASE: chatDB
        ports:
            - 27017:27017
        volumes:
            - mongo:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo: