_format_version: "3.0"

routes:
  - name: chat-route
    paths:
      - /api/chat
    service: chat-service

services:
  - name: chat-service
    url: http://chat-service-upstream # upstream 이름

  # JSON Mock Server
  - name: mock-service
    url: http://mock-server:3999 # 주의: docker container 이름과 같아야 함!
    routes:
      - name: mock-route
        paths:
          - /mock

upstreams:
  - name: chat-service-upstream
    targets:
      - target: chat-1:8200
        weight: 50
      - target: chat-2:8201
        weight: 50
    healthchecks:
      active:
        http_path: /health
