_format_version: "3.0"

routes:
  - name: chat-route
    paths:
      - /api/chat
    service: chat-service

services:
  - name: chat-service
    url: http://chat-service-upstream # upstream 이름

upstreams:
  - name: chat-service-upstream
    targets:
      - target: chat-service-1:3001
        weight: 50
      - target: chat-service-2:3101
        weight: 50
    healthchecks:
      active:
        http_path: /health
