name: kickzo

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    ports:
      - "${ELASTIC_PORT}:${ELASTIC_PORT}"
    environment:
      - discovery.type=single-node # 단일 노드로 실행
      - xpack.security.enabled=true
      - bootstrap.memory_lock=true # 메모리 잠금 활성화
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Elasticsearch JVM 메모리 설정
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=test123
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./elasticsearch-init.sh:/usr/share/elasticsearch/init.sh
    entrypoint: [ "/bin/sh", "-c", "/usr/share/elasticsearch/init.sh & /usr/local/bin/docker-entrypoint.sh" ]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - kickzo-network
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  es-data:

networks:
  kickzo-network:
    driver: bridge