global:
  scrape_interval: 5s # 5초마다 데이터를 수집

scrape_configs:
  - job_name: 'history-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['history:8080']  # Spring Boot 컨테이너 주소

  - job_name: 'state-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['state:8080']  # Spring Boot 컨테이너 주소

  - job_name: 'chat1-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['chat-1:8080']  # Spring Boot 컨테이너 주소

  - job_name: 'chat2-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['chat-2:8080']  # Spring Boot 컨테이너 주소

  - job_name: 'main-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['main:8080']  # Spring Boot 컨테이너 주소

  - job_name: 'mysql-monitoring'
    static_configs:
      - targets: ['mysql-exporter:9104']

  - job_name: 'mongodb-monitoring'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'redis-monitoring'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'kafka-monitoring'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'kong-monitoring'
    static_configs:
      - targets: ['kong:8001']
  
  - job_name: "friend-monitoring"
    static_configs:
      - targets: ["friend:8107"]