global:
  scrape_interval: 5s # 5초마다 데이터를 수집

scrape_configs:
  - job_name: 'history-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['history:8080']  # Spring Boot 컨테이너 주소

  - job_name: 'state-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['state:8080']  # Spring Boot 컨테이너 주소

  - job_name: 'chat1-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['chat-1:8080']  # Spring Boot 컨테이너 주소

  - job_name: 'chat2-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['chat-2:8080']  # Spring Boot 컨테이너 주소