plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.2'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)  // Java 17 사용
	}
}

repositories {
	mavenCentral()  // Maven Central 리포지토리 사용
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'software.amazon.awssdk:s3:2.20.6'

	implementation 'software.amazon.awssdk:auth:2.20.6'
	implementation 'software.amazon.awssdk:regions:2.20.6'
	implementation 'org.projectlombok:lombok'

	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()  // JUnit 플랫폼 사용
}
