name: kickzo

services:
  state:
    build:
      context: .
    container_name: state
    environment:
      - SPRING_PROFILES_ACTIVE=docker # Docker 환경에서 실행 시 'docker' 프로파일 사용
      - SERVER_PORT=${STATE_PORT} # server.port 설정
    ports:
      - "${STATE_PORT}:${STATE_PORT}"
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - kickzo-network

networks:
  kickzo-network:
    driver: bridge
