spring.application.name=state

server.port=8104

spring.profiles.active=dev

spring.kafka.consumer.group-id=my-group-${server.port}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

