name: kickzo

services:
  # Kong API Gateway
  kong:
    build:
      context: ./kong
    container_name: kong
    environment:
      - KONGADMIN_LISTEN=0.0.0.:${KONG_ADMIN_HTTP_PORT}
      - KONG_ADMIN_GUI_URL=http://localhost:${KONG_ADMIN_GUI_PORT}
    ports:
      - "${KONG_PROXY_HTTP_PORT}:${KONG_PROXY_HTTP_PORT}"
      - "${KONG_PROXY_SSL_PORT}:${KONG_PROXY_SSL_PORT}"
      - "${KONG_ADMIN_HTTP_PORT}:${KONG_ADMIN_HTTP_PORT}"
      - "${KONG_ADMIN_SSL_PORT}:${KONG_ADMIN_SSL_PORT}"
      - "${KONG_ADMIN_GUI_PORT}:${KONG_ADMIN_GUI_PORT}"
      - "${KONG_ADMIN_GUI_SSL_PORT}:${KONG_ADMIN_GUI_SSL_PORT}"
      - "${KONG_CUSTOM_PORT_1}:${KONG_CUSTOM_PORT_1}"
      - "${KONG_CUSTOM_PORT_2}:${KONG_CUSTOM_PORT_2}"
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
    networks:
      - kickzo-network

  # JSON Mock Server
  mock-server:
    build:
      context: ./mock
    container_name: mock-server
    ports:
      - "${MOCK_PORT}:${MOCK_PORT}"
    environment:
      - MOCK_PORT=${MOCK_PORT}
    volumes:
      - ./mock/db.json:/usr/src/app/db.json
    networks:
      - kickzo-network
    profiles:
      - mock

networks:
  kickzo-network:
    driver: bridge
