version: "3.9"

name: kickzo

services:
  # Redis
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - kickzo-network

  # Chat Service
  chat-service-1:
    build:
      context: ../backend/chat-service
    container_name: chat-service-1
    ports:
      - "${CHAT_PORT}:${CHAT_PORT}"
    environment:
      - CHAT_PORT=${CHAT_PORT}
    volumes:
      - ../backend/chat-service:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - kickzo-network
    depends_on:
      - redis-server

  chat-service-2:
    build:
      context: ../backend/chat-service
    container_name: chat-service-2
    ports:
      - "3101:3101"
    environment:
      - CHAT_PORT=3101
    volumes:
      - ../backend/chat-service:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - kickzo-network
    depends_on:
      - redis-server

  # Kong API Gateway
  kong:
    build:
      context: ./kong
    container_name: kong
    ports:
      - "${KONG_PROXY_HTTP_PORT}:${KONG_PROXY_HTTP_PORT}"
      - "${KONG_PROXY_SSL_PORT}:${KONG_PROXY_SSL_PORT}"
      - "${KONG_ADMIN_HTTP_PORT}:${KONG_ADMIN_HTTP_PORT}"
      - "${KONG_ADMIN_SSL_PORT}:${KONG_ADMIN_SSL_PORT}"
      - "${KONG_ADMIN_GUI_PORT}:${KONG_ADMIN_GUI_PORT}"
      - "${KONG_ADMIN_GUI_SSL_PORT}:${KONG_ADMIN_GUI_SSL_PORT}"
      - "${KONG_CUSTOM_PORT_1}:${KONG_CUSTOM_PORT_1}"
      - "${KONG_CUSTOM_PORT_2}:${KONG_CUSTOM_PORT_2}"
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
    networks:
      - kickzo-network

  # JSON Mock Server
  mock-server:
    build:
      context: ./mock
    container_name: mock-server
    ports:
      - "${MOCK_PORT}:${MOCK_PORT}"
    environment:
      - MOCK_PORT=${MOCK_PORT}
    volumes:
      - ./mock/db.json:/usr/src/app/db.json
    networks:
      - kickzo-network
    profiles:
      - mock

networks:
  kickzo-network:
    driver: bridge
