version: '3.8'

services:
  mysql:
    build:
      context: .
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: kickzo
      MYSQL_USER: kickzo
      MYSQL_PASSWORD: test123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
