name: CI
on:
  push:
    paths:
      - "src/frontend/**"
  workflow_dispatch:

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: src/frontend

      - name: Run Lint
        run: pnpm run lint
        working-directory: src/frontend

      - name: Run Build
        run: pnpm run build
        working-directory: src/frontend
